spring:
  application:
    name: spring-boot-grpc-server
  data:
    solr:
      host: http://solr.rd.wanfangdata.com.cn/solr
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache-setting.xml
  redis:
    host: access.limit.redis.host
    port: 6379
    timeout: 2000
    jedis:
      pool:
        max-active: 50
        max-idle: 10
        max-wait: 3000ms
        min-idle: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.10.184.172:3306/cpc-admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: wftest@231
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 10000
grpc:
  server:
    port: 9903
logging:
  file: logs/search.log
  level:
    root: info
    com.wanfangdata.grpc.server: info
auth:
  url: http://my.test.wanfangdata.com.cn/auth/
map:
  dbMap:
    LocalChronicleItemPersonage: 3
    LocalChroniclePersonage: 3
    LocalChronicleItemDialect: 5
    LocalChronicleDialect: 5
    LocalChronicleItemOpera: 4
    LocalChronicleEdu: 2
    LocalChronicleItemEdu: 2
    LocalChronicleOpera: 4
  coreMap:
    LocalChronicleItemPersonage: 'FZCPCLocalChronicleItem'
    LocalChroniclePersonage: 'FZCPCLocalChronicle'
    LocalChronicleItemDialect: 'FZCPCLocalChronicleItem'
    LocalChronicleDialect: 'FZCPCLocalChronicle'
    LocalChronicleEdu: 'FZCPCLocalChronicle'
    LocalChronicleItemEdu: 'FZCPCLocalChronicleItem'
    LocalChronicleItemOpera: 'FZCPCLocalChronicleItem'
    LocalChronicleOpera: 'FZCPCLocalChronicle'
  columMap:
    CategoryA: 'CategoryA'
    CategoryB: 'CategoryB'
    ColumnId: 'ColumnId'
  dialectMap:
    LocalChronicleItemDialect: '语音语法'
    LocalChronicleDialect: '区域划分'








